@data_service = http://localhost:8081/v1/data

### Создание данных
POST {{data_service}}/create
Content-Type: application/json

{
  "user_id": "550e8400-e29b-41d4-a716-446655440000",
  "type": "LOGIN_PASSWORD",
  "data": "c29tZSBkYXRh",
  "metadata": {
    "website": "example.com",
    "username": "user123"
  }
}

> {%
  if (response.status === 200) {
    client.global.set("data_id", response.body.dataId);
  } else {
    client.log("Ошибка: " + response.body.message);
  }
%}

### Получение данных
POST {{data_service}}/get
Content-Type: application/json

{
  "user_id": "550e8400-e29b-41d4-a716-446655440000",
  "data_id": "{{data_id}}"
}

> {%
  if (response.status === 200) {
    client.global.set("data_type", response.body.type);
    client.global.set("data_content", response.body.data);
    client.global.set("data_metadata", response.body.metadata);
  } else {
    client.log("Ошибка: " + response.body.message);
  }
%}

### Обновление данных
PUT {{data_service}}/update
Content-Type: application/json

{
  "user_id": "550e8400-e29b-41d4-a716-446655440000",
  "data_id": "{{data_id}}",
  "data": "dXBkYXRlZCBkYXRh",
  "metadata": {
    "website": "example.com",
    "username": "updated_user"
  }
}

> {%
  if (response.status === 200) {
    client.global.set("update_message", response.body.message);
  } else {
    client.log("Ошибка: " + response.body.message);
  }
%}

### Удаление данных
POST {{data_service}}/delete
Content-Type: application/json

{
  "user_id": "550e8400-e29b-41d4-a716-446655440000",
  "data_id": "{{data_id}}"
}

> {%
  if (response.status === 200) {
    client.global.set("delete_message", response.body.message);
  } else {
    client.log("Ошибка: " + response.body.message);
  }
%}

### Получение всех данных
GET {{data_service}}/list
Content-Type: application/json

{
  "user_id": "550e8400-e29b-41d4-a716-446655440000"
}

> {%
  if (response.status === 200) {
    client.global.set("data_list", response.body.data);
  } else {
    client.log("Ошибка: " + response.body.message);
  }
%}