@sync_service = http://localhost:8082/v1/sync

### Синхронизация данных
POST {{sync_service}}/data
Content-Type: application/json

{
  "user_id": "550e8400-e29b-41d4-a716-446655440001",
  "client_data": [
    {
      "data_id": "660e8400-e29b-41d4-a716-446655440001",
      "type": "TEXT",
      "data": "sasdadasdasd",
      "operation": "UPDATE",
      "updated_at": 1698765432,
      "metadata": [
        {
          "key": "website",
          "value": "example.com"
        },
        {
          "key": "username",
          "value": "updated_user"
        }
      ]
    },
    {
      "data_id": "770e8400-e29b-41d4-a716-446655440002",
      "type": "CARD",
      "data": "asdsadadasdasd",
      "operation": "ADD",
      "updated_at": 1698765433,
      "metadata": [
        {
          "key": "website",
          "value": "another-example.com"
        },
        {
          "key": "username",
          "value": "new_user"
        }
      ]
    }
  ]
}

> {%
  if (response.status === 200) {
    client.global.set("sync_conflicts", response.body.conflicts);
  } else {
    client.log("Ошибка: " + response.body.message);
  }
%}

### Разрешение конфликта
POST {{sync_service}}/resolve-conflict
Content-Type: application/json

{
  "user_id": "550e8400-e29b-41d4-a716-446655440001",
  "conflictId": "8006b343-334a-4727-beff-2cee4552066f",
  "strategy": "USE_CLIENT_VERSION"
}
> {%
  if (response.status === 200) {
    client.global.set("resolve_message", response.body.message);
  } else {
    client.log("Ошибка: " + response.body.message);
  }
%}

### Получение списка конфликтов
GET {{sync_service}}/conflicts?user_id=550e8400-e29b-41d4-a716-446655440001
Content-Type: application/json

> {%
  if (response.status === 200) {
    client.global.set("conflicts", response.body.conflicts);
  } else {
    client.log("Ошибка: " + response.body.message);
  }
%}
