coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        threshold: 1%
        target: 80%
    patch:
      default:
        threshold: 1%
        target: 80%

github_checks:
  annotations: false

ignore:
  - "**/*_mock.go"
  - "pkg/**"
  - "vendor/**"
  - "vendor.pb/**"
  - "client/**"
  - "cmd/**"

