coverage:
  precision: 2
  round: down
  range: "40...100"

  status:
    project:
      default:
        threshold: 1%
        target: 60%
    patch:
      default:
        threshold: 1%
        target: 60%

github_checks:
  annotations: false

ignore:
  - "**/*_mock.go"
  - "pkg/**"
  - "vendor/**"
  - "vendor.pb/**"

