version: "3.7"
services:
  postgres:
    image: postgres:13.10-alpine
    container_name: manager
    ports:
      - 5555:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./local/init_db.sql:/docker-entrypoint-initdb.d/db.sql
    mem_limit: 1024m
    healthcheck:
      test: bash -c '((echo >/dev/tcp/localhost/5432) &>/dev/null)'
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - common
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

networks:
  common:
    driver: bridge

volumes:
  postgres:
    driver: local
